import type { Word } from './types'

export const words: Word[] = [
  // Módulo 1: Gramática esencial
  {
    es: 'hay',
    context: 'Para dizer que algo existe: o "tem" de "tem um bug"',
    pt: 'tem, há (existir)',
    examples: ['**Hay** un bug en el login.', 'No **hay** tests para este módulo.'],
    module: 1,
  },
  {
    es: 'tener que',
    context: 'Para falar de obrigação ou do que precisa ser feito',
    pt: 'ter que',
    examples: ['**Tengo que** salir a las cinco.', '**Tenemos que** hablar con producto.'],
    module: 1,
  },
  {
    es: 'listo',
    context: 'Com estar: algo terminado. Com ser: pessoa esperta',
    pt: 'pronto (estar listo) / esperto (ser listo)',
    examples: ['El deploy está **listo**.', 'El PR está **listo**.'],
    module: 1,
  },
  {
    es: 'lo importante',
    context: 'Lo + adjetivo para falar de uma ideia, nunca "el importante"',
    pt: 'o importante',
    examples: ['**Lo importante** es que funcione.'],
    module: 1,
  },
  {
    es: 'lo que',
    context: 'Para explicar uma situação ou retomar o que alguém disse',
    pt: 'o que',
    examples: ['**Lo que** pasa es que el test falla en CI.', 'No entiendo **lo que** dices.'],
    module: 1,
  },
  {
    es: 'tampoco',
    context: 'Negar junto com alguém; nunca "también no"',
    pt: 'também não',
    examples: ['A mí **tampoco** me funciona en Safari.'],
    module: 1,
  },
  {
    es: 'ya no',
    context: 'Para dizer que algo deixou de acontecer',
    pt: 'não … mais',
    examples: ['El error **ya no** aparece en los logs.'],
    module: 1,
  },
  {
    es: '¿cuál?',
    context: 'Para pedir um dado ou escolher entre opções',
    pt: 'qual?',
    examples: ['¿**Cuál** es la URL?'],
    module: 1,
  },
  {
    es: 'por qué / porque',
    context: 'Separado e com acento na pergunta, junto na resposta',
    pt: 'por quê / porque',
    examples: ['¿**Por qué** falla? **Porque** falta una variable de entorno.'],
    module: 1,
  },
  {
    es: 'ustedes',
    context: 'O "vocês" da América Latina, em qualquer situação',
    pt: 'vocês',
    examples: ['¿**Ustedes** usan TypeScript?'],
    module: 1,
  },
  {
    es: 'usted',
    context: 'Formal, para clientes; no time, use tú',
    pt: 'o senhor, a senhora',
    examples: ['¿**Usted** puede compartir pantalla?'],
    module: 1,
  },
  {
    es: 'lo / la',
    context: 'Objeto direto antes do verbo, no lugar de "revisei ele"',
    pt: 'o, a (ele, ela como objeto)',
    examples: ['¿El PR? **Lo** reviso ahora.', '**Lo** voy a revisar.'],
    module: 1,
  },
  {
    es: 'le / les',
    context: 'Objeto indireto: para quem você manda ou diz algo',
    pt: 'lhe, para ele / para ela',
    examples: ['**Le** mandé el enlace a Ana.'],
    module: 1,
  },
  {
    es: 'se lo',
    context: 'Quando le/les encontra lo/la numa mesma frase',
    pt: 'mando isso para ele / ela',
    examples: ['¿El informe? **Se lo** envío mañana.'],
    module: 1,
  },
  {
    es: 'ir a + infinitivo',
    context: 'Na daily, para dizer o que vai fazer; não esqueça o "a"',
    pt: 'ir + infinitivo (vou fazer)',
    examples: ['**Voy a** revisar el PR.', 'Hoy estoy con los tests y **voy a** subir el PR por la tarde.'],
    module: 1,
  },
  {
    es: 'el mensaje',
    context: 'Gênero diferente: masculino em espanhol',
    pt: 'a mensagem',
    examples: ['Te mandé **el mensaje** por Slack.'],
    module: 1,
  },
  {
    es: 'el lenguaje',
    context: 'Gênero diferente: palavras em -aje são masculinas',
    pt: 'a linguagem',
    examples: ['TypeScript es **el lenguaje** del proyecto.'],
    module: 1,
  },
  {
    es: 'el análisis',
    context: 'Gênero diferente: masculino em espanhol',
    pt: 'a análise',
    examples: ['**El análisis** del incidente está en la doc.'],
    module: 1,
  },
  {
    es: 'la alarma',
    context: 'Gênero diferente: feminino em espanhol',
    pt: 'o alarme',
    examples: ['**La alarma** de CPU sonó a las tres.'],
    module: 1,
  },
  {
    es: 'la computadora',
    context: 'América Latina; na Espanha dizem "el ordenador"',
    pt: 'o computador',
    examples: ['Voy a reiniciar **la computadora**.'],
    module: 1,
  },
  {
    es: 'tomar',
    context: 'Use no lugar de "coger", que é palavrão em vários países',
    pt: 'pegar',
    examples: ['**Tomo** el ticket.'],
    module: 1,
  },
  {
    es: 'el jefe',
    context: 'Palavra do texto de El Dorado',
    pt: 'o chefe, o líder',
    examples: ['**El jefe** sube a una balsa con sus acompañantes.'],
    module: 1,
  },
  {
    es: 'tirar',
    context: 'Palavra do texto: jogar algo fora ou longe',
    pt: 'jogar, atirar',
    examples: ['**Tira** oro y esmeraldas al agua.'],
    module: 1,
  },
  {
    es: 'vaciar',
    context: 'Esvaziar uma tabela, uma fila ou um cache',
    pt: 'esvaziar',
    examples: ['Incluso intentaron **vaciar** el lago para sacar el oro.'],
    module: 1,
  },

  // Módulo 2: Conectores y frases
  {
    es: 'pero',
    context: 'Para contrastar; é o "porém", não "todavía"',
    pt: 'mas, porém',
    examples: ['Funciona, **pero** es lento.'],
    module: 2,
  },
  {
    es: 'sino',
    context: 'Depois de uma negação, para corrigir: não é isso, é aquilo',
    pt: 'mas sim, e sim',
    examples: ['No es un bug, **sino** una feature.', 'No es un problema de red, **sino** de DNS.'],
    module: 2,
  },
  {
    es: 'si no',
    context: 'Separado é condição, não confunda com sino',
    pt: 'se não',
    examples: ['**Si no** funciona, avísame.'],
    module: 2,
  },
  {
    es: 'aunque',
    context: 'Para admitir algo e seguir; com fato, verbo normal',
    pt: 'embora, mesmo que',
    examples: ['**Aunque** pasa los tests, falla en staging.', '**Aunque** el cambio es pequeño, necesita review.'],
    module: 2,
  },
  {
    es: 'todavía',
    context: 'Falso amigo: na daily, para dizer o que ainda falta',
    pt: 'ainda',
    examples: ['**Todavía** no revisé tu PR.', '¿**Todavía** estás en la reunión?'],
    module: 2,
  },
  {
    es: 'aún',
    context: 'Com acento, sinônimo de todavía',
    pt: 'ainda',
    examples: ['**Aún** no está listo.'],
    module: 2,
  },
  {
    es: 'ya',
    context: 'Para dizer que algo já foi feito',
    pt: 'já',
    examples: ['**Ya** está en producción.', '**Ya** lo arreglé.'],
    module: 2,
  },
  {
    es: 'además',
    context: 'Para somar mais uma informação',
    pt: 'além disso',
    examples: ['**Además**, hay que actualizar la doc.', '**Además del** backend, hago el front.'],
    module: 2,
  },
  {
    es: 'sin embargo',
    context: 'Contraste por escrito: docs, e-mails, descrição de PR',
    pt: 'no entanto',
    examples: ['El cambio es pequeño. **Sin embargo**, afecta a todo el login.'],
    module: 2,
  },
  {
    es: 'entonces',
    context: 'Para concluir ou seguir a conversa',
    pt: 'então',
    examples: ['**Entonces**, ¿lo desplegamos hoy?'],
    module: 2,
  },
  {
    es: 'así que',
    context: 'Para dizer a consequência, no meio da frase',
    pt: 'então, por isso',
    examples: ['La API estaba caída, **así que** reinicié el servicio.'],
    module: 2,
  },
  {
    es: 'por eso',
    context: 'Consequência; "isso" em espanhol é "eso"',
    pt: 'por isso',
    examples: ['El test fallaba a veces, **por eso** lo desactivé.'],
    module: 2,
  },
  {
    es: 'o sea',
    context: 'Na fala, para explicar de novo (às vezes como pausa)',
    pt: 'ou seja',
    examples: ['Falla en staging, **o sea**, hoy no desplegamos.'],
    module: 2,
  },
  {
    es: 'es decir',
    context: 'Versão mais formal de "o sea", boa para docs',
    pt: 'isto é, ou seja',
    examples: ['El endpoint es idempotente, **es decir**, se puede llamar varias veces.'],
    module: 2,
  },
  {
    es: 'antes de',
    context: 'Seguido de infinitivo, para ordenar passos',
    pt: 'antes de',
    examples: ['**Antes de** desplegar, corro los tests.'],
    module: 2,
  },
  {
    es: 'después de',
    context: 'Seguido de infinitivo, para contar a sequência',
    pt: 'depois de',
    examples: ['**Después de** revisar el PR, lo aprobé.'],
    module: 2,
  },
  {
    es: 'bueno',
    context: 'Muletilla para começar uma resposta',
    pt: 'bom…',
    examples: ['**Bueno**, depende de cuántos usuarios esperamos.'],
    module: 2,
  },
  {
    es: 'a ver',
    context: 'Muletilla antes de analisar algo',
    pt: 'vamos ver…',
    examples: ['**A ver**… creo que el problema está en el cache.'],
    module: 2,
  },
  {
    es: 'déjame pensar',
    context: 'Para ganhar alguns segundos numa reunião',
    pt: 'deixa eu pensar',
    examples: ['**Déjame pensar**… creo que es un problema de caché.'],
    module: 2,
  },
  {
    es: '¿cómo se dice…?',
    context: 'Quando falta a palavra no meio da frase',
    pt: 'como se diz…?',
    examples: ['¿**Cómo se dice**…? El rollback.'],
    module: 2,
  },
  {
    es: '¿no?',
    context: 'No fim da frase, no lugar do "né?"',
    pt: 'né?',
    examples: ['Es más rápido con un índice, **¿no?**'],
    module: 2,
  },
  {
    es: 'como',
    context: 'Para comparar, no lugar do "tipo…"',
    pt: 'tipo, como',
    examples: ['Es **como** un proxy, pero más simple.'],
    module: 2,
  },
  {
    es: '¿me explico?',
    context: 'Para conferir se foi entendido',
    pt: 'fui claro?',
    examples: ['Primero migramos y después borramos la tabla. **¿Me explico?**'],
    module: 2,
  },
  {
    es: '¿me sigues?',
    context: 'Para conferir se a pessoa está acompanhando',
    pt: 'está me acompanhando?',
    examples: ['El evento va a la cola y de ahí al servicio. **¿Me sigues?**'],
    module: 2,
  },
  {
    es: 'tarde o temprano',
    context: 'Palavra do texto de La Llorona',
    pt: 'cedo ou tarde',
    examples: ['**Tarde o temprano** alguien te la va a contar.'],
    module: 2,
  },
  {
    es: 'enojarse',
    context: 'Palavra do texto: ficar bravo com alguém',
    pt: 'ficar bravo',
    examples: ['Una mujer **se enojó** con su esposo.'],
    module: 2,
  },
  {
    es: 'por si acaso',
    context: 'Para ter um plano B, como um vídeo na demo',
    pt: 'por via das dúvidas',
    examples: ['Tengo un video, **por si acaso**.'],
    module: 2,
  },

  // Módulo 3: Vocabulario del día a día
  {
    es: 'borrar',
    context: 'Falso amigo: é deletar, não "apagar"',
    pt: 'apagar, deletar',
    examples: ['**Borré** la rama vieja.', 'Antes de correr el script, no **borres** nada.'],
    module: 3,
  },
  {
    es: 'apagar',
    context: 'Falso amigo: é desligar, não deletar',
    pt: 'desligar',
    examples: ['**Apagué** el servidor de staging.'],
    module: 3,
  },
  {
    es: 'prender',
    context: 'Falso amigo: ligar um aparelho (também "encender")',
    pt: 'ligar',
    examples: ['¿Puedes **prender** la cámara?'],
    module: 3,
  },
  {
    es: 'pronto',
    context: 'Falso amigo: é "logo"; o "pronto" do português é listo',
    pt: 'logo, em breve',
    examples: ['Lo termino **pronto**.'],
    module: 3,
  },
  {
    es: 'un rato',
    context: 'Falso amigo: um período curto de tempo',
    pt: 'um tempinho',
    examples: ['Nadie dijo nada durante **un rato**.'],
    module: 3,
  },
  {
    es: 'largo',
    context: 'Falso amigo: não é "largo" em português',
    pt: 'comprido, longo',
    examples: ['Este PR es muy **largo**, ¿lo dividimos?'],
    module: 3,
  },
  {
    es: 'contestar',
    context: 'Falso amigo: responder, não discordar',
    pt: 'responder',
    examples: ['Mi líder **contestó**: «Tranquilo, la prendemos otra vez».'],
    module: 3,
  },
  {
    es: 'oficina',
    context: 'Falso amigo: o escritório, não uma oficina mecânica',
    pt: 'escritório',
    examples: ['Mañana voy a la **oficina**.'],
    module: 3,
  },
  {
    es: 'acordar',
    context: 'Falso amigo: combinar algo com o time',
    pt: 'combinar',
    examples: ['**Acordamos** desplegar el lunes.'],
    module: 3,
  },
  {
    es: 'acordarse de',
    context: 'Para lembrar de algo; acordar do sono é despertarse',
    pt: 'lembrar',
    examples: ['¿**Te acuerdas de** la contraseña?'],
    module: 3,
  },
  {
    es: 'exquisito',
    context: 'Falso amigo: não é "esquisito" em português (raro)',
    pt: 'delicioso',
    examples: ['El café de la oficina es **exquisito**.'],
    module: 3,
  },
  {
    es: 'embarazada',
    context: 'Falso amigo: envergonhada é "avergonzada"',
    pt: 'grávida',
    examples: ['Ana está **embarazada** y sale de licencia en marzo.'],
    module: 3,
  },
  {
    es: 'la cadena',
    context: 'Ao explicar código: o tipo string',
    pt: 'a string',
    examples: ['La función recibe una **cadena** y devuelve un número.'],
    module: 3,
  },
  {
    es: 'el arreglo',
    context: 'Ao explicar código: o array',
    pt: 'o array',
    examples: ['La función recibe un **arreglo** de usuarios y devuelve solo los activos.'],
    module: 3,
  },
  {
    es: 'vacío',
    context: 'Uma lista, string ou tabela sem nada',
    pt: 'vazio',
    examples: ['Si la lista está **vacía**, lanza una excepción.'],
    module: 3,
  },
  {
    es: 'devolver',
    context: 'O que uma função retorna (também "retornar")',
    pt: 'retornar, devolver',
    examples: ['La función recibe un arreglo de usuarios y **devuelve** solo los activos.'],
    module: 3,
  },
  {
    es: 'recorrer',
    context: 'Percorrer um array num loop',
    pt: 'percorrer',
    examples: ['**Recorre** el arreglo y, si un usuario es nulo, lo ignora.'],
    module: 3,
  },
  {
    es: 'correr',
    context: 'Rodar testes ou scripts; nunca "rodar"',
    pt: 'rodar, executar',
    examples: ['Antes de desplegar, **corro** los tests.'],
    module: 3,
  },
  {
    es: 'agregar',
    context: 'Adicionar algo ao código (na Espanha, "añadir")',
    pt: 'adicionar',
    examples: ['Una cola **agrega** otro servicio que mantener.'],
    module: 3,
  },
  {
    es: 'lanzar una excepción',
    context: 'Ao explicar o que acontece num caso de erro',
    pt: 'lançar uma exceção',
    examples: ['Si la lista está vacía, **lanza una excepción**.'],
    module: 3,
  },
  {
    es: 'llevar + tempo',
    context: 'Para dizer há quanto tempo você faz algo',
    pt: 'estar há (tempo)',
    examples: ['**Llevo** dos años en la empresa.', 'Esto va a **llevar** tres días.'],
    module: 3,
  },
  {
    es: 'encargarse de',
    context: 'Na apresentação, para dizer do que você cuida',
    pt: 'cuidar de, ser responsável por',
    examples: ['**Me encargo de** la API de pagos.'],
    module: 3,
  },
  {
    es: 'desarrollador',
    context: 'O cargo; nunca "desenvolvedor"',
    pt: 'desenvolvedor',
    examples: ['Trabajo como **desarrollador** backend.'],
    module: 3,
  },
  {
    es: 'el equipo',
    context: 'O time de trabalho; "time" não existe nesse sentido',
    pt: 'o time, a equipe',
    examples: ['Llevo dos años en el **equipo**.'],
    module: 3,
  },
  {
    es: 'encantado',
    context: 'Ao ser apresentado; concorda com quem fala',
    pt: 'prazer',
    examples: ['Hola a todos, me llamo Lucas. ¡**Encantado**!'],
    module: 3,
  },
  {
    es: 'las llaves',
    context: 'Ao ditar código: { }, não "chaves"',
    pt: 'as chaves { }',
    examples: ['if, abre paréntesis, user punto isActive, cierra paréntesis, abre **llave**'],
    module: 3,
  },
  {
    es: 'los corchetes',
    context: 'Ao ditar código: [ ], não "colchetes"',
    pt: 'os colchetes [ ]',
    examples: ['items, abre **corchete**, cero, cierra **corchete**'],
    module: 3,
  },
  {
    es: 'el guion bajo',
    context: 'Ao ditar código: o caractere _',
    pt: 'o underscore',
    examples: ['MAX_RETRIES, todo en mayúsculas y con **guion bajo**.'],
    module: 3,
  },
  {
    es: 'quedar',
    context: 'Palavra do texto: como algo ficou no fim',
    pt: 'ficar',
    examples: ['En dos segundos, la tabla de usuarios **quedó** vacía.'],
    module: 3,
  },

  // Módulo 4: La daily y las tareas
  {
    es: 'seguir con',
    context: 'Na daily, para dizer que continua uma tarefa',
    pt: 'continuar com',
    examples: ['Hoy voy a **seguir con** el ticket de pagos.'],
    module: 4,
  },
  {
    es: 'empezar',
    context: 'Na daily, para dizer o que vai começar (empiezo)',
    pt: 'começar',
    examples: ['Hoy voy a terminar el PR y, si hay tiempo, **empiezo** con la doc.'],
    module: 4,
  },
  {
    es: 'subir un PR',
    context: 'Abrir um pull request',
    pt: 'abrir um PR',
    examples: ['Ayer terminé el endpoint de login y **subí el PR**.'],
    module: 4,
  },
  {
    es: 'desplegar',
    context: 'Fazer deploy de uma versão',
    pt: 'fazer deploy',
    examples: ['Antes de **desplegar**, corro los tests.', 'Entonces, ¿lo **desplegamos** hoy?'],
    module: 4,
  },
  {
    es: 'probar',
    context: 'Testar algo (pruebo)',
    pt: 'testar',
    examples: ['Uso un mock para **probar** el servicio.'],
    module: 4,
  },
  {
    es: 'estar bloqueado',
    context: 'Na daily, para dizer o que te impede de avançar',
    pt: 'estar bloqueado',
    examples: ['**Estoy bloqueado** por el acceso a staging.'],
    module: 4,
  },
  {
    es: 'necesitar',
    context: 'Sem "de" depois do verbo',
    pt: 'precisar de',
    examples: ['**Necesito** acceso a staging.'],
    module: 4,
  },
  {
    es: 'trabado',
    context: 'Com "b": quando você está travado num problema',
    pt: 'travado',
    examples: ['Estoy **trabado** con este bug.'],
    module: 4,
  },
  {
    es: 'la historia de usuario',
    context: 'Na planning: a user story',
    pt: 'a user story',
    examples: ['Falta dividir **la historia de usuario** en tareas.'],
    module: 4,
  },
  {
    es: 'los criterios de aceptación',
    context: 'Na planning: o que define que o ticket está pronto',
    pt: 'os critérios de aceite',
    examples: ['¿Cuáles son **los criterios de aceptación**?'],
    module: 4,
  },
  {
    es: 'la estimación',
    context: 'Na planning; nunca "la estimativa"',
    pt: 'a estimativa',
    examples: ['Mi **estimación** es de tres puntos.'],
    module: 4,
  },
  {
    es: 'el alcance',
    context: 'Na planning; nunca "el escopo"',
    pt: 'o escopo',
    examples: ['¿Cuál es **el alcance**?', 'Podemos sacar los gráficos del **alcance**.'],
    module: 4,
  },
  {
    es: 'el plazo',
    context: 'A data limite de uma entrega',
    pt: 'o prazo',
    examples: ['Con este **plazo** no llegamos con todo.'],
    module: 4,
  },
  {
    es: 'poner puntos',
    context: 'Ao estimar um ticket na planning',
    pt: 'dar pontos',
    examples: ['Le **pongo** cinco **puntos**.'],
    module: 4,
  },
  {
    es: 'avisar',
    context: 'Te aviso para uma pessoa, les aviso para o time',
    pt: 'avisar',
    examples: ['Les **aviso** que el ticket de reportes se va a retrasar.', 'Cuando termine el deploy, te **aviso**.'],
    module: 4,
  },
  {
    es: 'retrasarse',
    context: 'Para avisar que uma entrega vai atrasar',
    pt: 'atrasar',
    examples: ['El ticket de reportes **se va a retrasar** un día.'],
    module: 4,
  },
  {
    es: 'no llegar',
    context: 'Para dizer que não vai dar tempo até o prazo',
    pt: 'não conseguir entregar',
    examples: ['**No voy a llegar** para el viernes.'],
    module: 4,
  },
  {
    es: 'la demora',
    context: 'Para pedir desculpa pelo atraso: perdón por la demora',
    pt: 'a demora',
    examples: ['Perdón por **la demora**, ya subí el PR.'],
    module: 4,
  },
  {
    es: '¿qué les parece si…?',
    context: 'Para propor uma saída ao time',
    pt: 'o que acham se…?',
    examples: ['¿**Qué les parece si** lo dividimos en dos tickets?'],
    module: 4,
  },
  {
    es: 'fallar',
    context: 'Num ticket ou incidente, quando algo não funciona',
    pt: 'falhar',
    examples: ['El checkout **falla** con tarjetas internacionales.'],
    module: 4,
  },
  {
    es: 'estar caído',
    context: 'Serviço fora do ar; nunca "fuera del aire"',
    pt: 'estar fora do ar',
    examples: ['El login **está caído** desde las 10:15.', 'La API **está caída**.'],
    module: 4,
  },
  {
    es: 'estar roto',
    context: 'Num ticket, para algo quebrado',
    pt: 'estar quebrado',
    examples: ['El botón de guardar **está roto** en Safari.'],
    module: 4,
  },
  {
    es: 'colgarse',
    context: 'Quando a app ou a página trava',
    pt: 'travar',
    examples: ['La app **se cuelga** cuando subo un archivo grande.'],
    module: 4,
  },
  {
    es: 'debería',
    context: 'Num ticket, para o resultado esperado',
    pt: 'deveria',
    examples: ['El botón **debería** guardar los cambios, pero no hace nada.'],
    module: 4,
  },
  {
    es: 'volver a + infinitivo',
    context: 'Para dizer que algo aconteceu de novo',
    pt: 'voltar a, fazer de novo',
    examples: ['El error **volvió a** aparecer.', 'Hicimos rollback y el servicio **volvió a** funcionar.'],
    module: 4,
  },
  {
    es: 'vencido',
    context: 'Num incidente: certificado ou token expirado',
    pt: 'expirado, vencido',
    examples: ['Ya está resuelto. La causa fue un certificado **vencido**.'],
    module: 4,
  },
  {
    es: 'los pasos para reproducir',
    context: 'Seção do ticket de bug',
    pt: 'os passos para reproduzir',
    examples: ['Abre un ticket con **los pasos para reproducir**.'],
    module: 4,
  },
  {
    es: 'descargar',
    context: 'Baixar um arquivo',
    pt: 'baixar (download)',
    examples: ['El cliente **descarga** sus datos en CSV.'],
    module: 4,
  },

  // Módulo 5: Pair programming y code review
  {
    es: '¿qué tal si…?',
    context: 'No pair ou no review, para sugerir sem impor',
    pt: 'que tal se…?',
    examples: ['¿**Qué tal si** extraemos esto a una función?'],
    module: 5,
  },
  {
    es: '¿y si…?',
    context: 'Para sugerir algo; depois de "si", verbo no presente',
    pt: 'e se…?',
    examples: ['¿**Y si** probamos con un índice?'],
    module: 5,
  },
  {
    es: 'podríamos',
    context: 'Para propor uma solução sem soar como ordem',
    pt: 'poderíamos',
    examples: ['**Podríamos** hacerlo así.'],
    module: 5,
  },
  {
    es: 'a lo mejor',
    context: 'Para levantar uma hipótese, com verbo normal',
    pt: 'talvez',
    examples: ['**A lo mejor** es el cache.'],
    module: 5,
  },
  {
    es: 'tener sentido',
    context: 'Para aceitar uma sugestão',
    pt: 'fazer sentido',
    examples: ['Buen punto. **Tiene sentido**.'],
    module: 5,
  },
  {
    es: 'tener razón',
    context: 'Para responder a um review ou concordar',
    pt: 'ter razão',
    examples: ['**Tienes razón**, ya lo cambié.'],
    module: 5,
  },
  {
    es: '¿me lo repites?',
    context: 'Numa call, quando você não entendeu',
    pt: 'pode repetir?',
    examples: ['Perdón, **¿me lo repites?**'],
    module: 5,
  },
  {
    es: 'despacio',
    context: 'Para pedir que falem mais devagar; nunca "devagar"',
    pt: 'devagar',
    examples: ['¿Puedes hablar más **despacio**?'],
    module: 5,
  },
  {
    es: 'se cortó el audio',
    context: 'Numa call, quando a conexão falha',
    pt: 'o áudio cortou',
    examples: ['Perdón, **se cortó el audio**. ¿Me lo repites?'],
    module: 5,
  },
  {
    es: '¿qué quieres decir con…?',
    context: 'Para pedir que expliquem um termo',
    pt: 'o que você quer dizer com…?',
    examples: ['¿**Qué quieres decir con** "pato de goma"?'],
    module: 5,
  },
  {
    es: 'si entendí bien',
    context: 'Para confirmar com suas palavras',
    pt: 'se entendi bem',
    examples: ['Entonces, **si entendí bien**, el cache se limpia cada hora.'],
    module: 5,
  },
  {
    es: 'la pantalla',
    context: 'A tela do computador; "tela" em espanhol é tecido',
    pt: 'a tela',
    examples: ['¿Quién comparte **pantalla**?', '¿Ves mi **pantalla**?'],
    module: 5,
  },
  {
    es: 'llevar el teclado',
    context: 'No pair, ser quem digita (driver)',
    pt: 'ser o driver, digitar',
    examples: ['Él **lleva el teclado** y ella guía.'],
    module: 5,
  },
  {
    es: '¿me pasas el teclado?',
    context: 'No pair, para trocar de driver',
    pt: 'me passa o teclado?',
    examples: ['**¿Me pasas el teclado?** Quiero probar algo.'],
    module: 5,
  },
  {
    es: 'dale',
    context: 'Para dizer "pode mandar" (América do Sul)',
    pt: 'vai, pode mandar',
    examples: ['¿Ves mi pantalla? Sí, **dale**.'],
    module: 5,
  },
  {
    es: 'volver atrás',
    context: 'No pair, para pedir que voltem no código',
    pt: 'voltar',
    examples: ['Espera, **vuelve atrás**.'],
    module: 5,
  },
  {
    es: 'hacer una pausa',
    context: 'Para parar alguns minutos durante o pair',
    pt: 'fazer uma pausa',
    examples: ['¿**Hacemos una pausa** de cinco minutos?'],
    module: 5,
  },
  {
    es: 'arreglar',
    context: 'Consertar um bug ou um comentário; nunca "arrumar"',
    pt: 'arrumar, consertar',
    examples: ['Buena observación. Lo **arreglé** en el último commit.'],
    module: 5,
  },
  {
    es: 'romper',
    context: 'No review, para um comentário bloqueante',
    pt: 'quebrar',
    examples: ['Esto **rompe** el login si el usuario es nulo.'],
    module: 5,
  },
  {
    es: 'el enfoque',
    context: 'No review, para elogiar ou discutir uma solução',
    pt: 'a abordagem',
    examples: ['Me gusta este **enfoque**.'],
    module: 5,
  },
  {
    es: 'echar un vistazo',
    context: 'No Slack, para pedir que olhem seu PR',
    pt: 'dar uma olhada',
    examples: ['¿Le puedes **echar un vistazo** a mi PR?'],
    module: 5,
  },
  {
    es: 'te dejo el link',
    context: 'No Slack, ao mandar um link',
    pt: 'te mando o link',
    examples: ['Es un cambio pequeño en el login. **Te dejo el link**.'],
    module: 5,
  },
  {
    es: 'cuando puedas',
    context: 'No Slack, para pedir algo sem pressionar',
    pt: 'quando puder',
    examples: ['¿Le puedes echar un vistazo a mi PR? **Cuando puedas**, gracias.'],
    module: 5,
  },
  {
    es: 'quedo atento',
    context: 'No fim de uma mensagem, esperando resposta',
    pt: 'fico no aguardo',
    examples: ['Te dejo el link del PR. **Quedo atento**.'],
    module: 5,
  },
  {
    es: '¿tienes un minuto?',
    context: 'No Slack, para abrir uma conversa',
    pt: 'tem um minuto?',
    examples: ['Hola, Sofía. **¿Tienes un minuto?** Un test del checkout falla solo a veces.'],
    module: 5,
  },
  {
    es: 'hacer de',
    context: 'Palavra do texto: fazer o papel de alguém',
    pt: 'fazer o papel de',
    examples: ['Yo solo **hice de** pato de goma.'],
    module: 5,
  },

  // Módulo 6: Reuniones y decisiones técnicas
  {
    es: 'la cola',
    context: 'Arquitetura: fila de mensagens; nunca "la fila"',
    pt: 'a fila',
    examples: ['El servicio manda un evento a **la cola**.'],
    module: 6,
  },
  {
    es: 'la capa',
    context: 'Arquitetura: camada; nunca "la camada"',
    pt: 'a camada',
    examples: ['La validación está en **la capa** de servicio.'],
    module: 6,
  },
  {
    es: 'el cuello de botella',
    context: 'Arquitetura: o ponto que limita o desempenho',
    pt: 'o gargalo',
    examples: ['La base de datos es **el cuello de botella**.'],
    module: 6,
  },
  {
    es: 'el balanceador de carga',
    context: 'Arquitetura: o load balancer',
    pt: 'o load balancer',
    examples: ['**El balanceador de carga** reparte el tráfico entre dos servidores.'],
    module: 6,
  },
  {
    es: 'comunicarse con',
    context: 'Para descrever como as partes do sistema conversam',
    pt: 'comunicar-se com',
    examples: ['El front **se comunica con** la API.'],
    module: 6,
  },
  {
    es: 'por un lado… por otro…',
    context: 'Para comparar dois lados de uma decisão',
    pt: 'por um lado… por outro…',
    examples: ['**Por un lado** es más rápido; **por otro**, es otro servicio que mantener.'],
    module: 6,
  },
  {
    es: 'la ventaja / la desventaja',
    context: 'Para comparar opções num trade-off',
    pt: 'a vantagem / a desvantagem',
    examples: ['Un monolito es más simple. **La desventaja** es que escala peor.'],
    module: 6,
  },
  {
    es: 'a cambio de',
    context: 'Para dizer o que se perde num trade-off',
    pt: 'em troca de',
    examples: ['Ganamos velocidad **a cambio de** complejidad.'],
    module: 6,
  },
  {
    es: 'valer la pena',
    context: 'Para defender uma escolha',
    pt: 'valer a pena',
    examples: ['Creo que **vale la pena**: el mes pasado perdimos dos mil correos.'],
    module: 6,
  },
  {
    es: 'por ahora',
    context: 'Para recomendar algo sem fechar o futuro',
    pt: 'por enquanto',
    examples: ['**Por ahora**, lo más simple es usar Postgres.'],
    module: 6,
  },
  {
    es: 'creo que',
    context: 'Para opinar; "achar" não existe em espanhol',
    pt: 'acho que',
    examples: ['**Creo que** vale la pena.'],
    module: 6,
  },
  {
    es: 'me parece que',
    context: 'Para dar uma opinião de forma suave',
    pt: 'me parece que',
    examples: ['**Me parece que** el problema está en las queries.'],
    module: 6,
  },
  {
    es: 'estar de acuerdo',
    context: 'Para concordar; sempre com estar, nunca "ser"',
    pt: 'concordar',
    examples: ['**Estoy de acuerdo** en parte.'],
    module: 6,
  },
  {
    es: 'me parece bien',
    context: 'Para aceitar uma proposta numa reunião',
    pt: 'por mim, tudo bem',
    examples: ['Martín lo piensa. «**Me parece bien**».'],
    module: 6,
  },
  {
    es: 'entiendo tu punto, pero…',
    context: 'Para discordar com educação',
    pt: 'entendo seu ponto, mas…',
    examples: ['**Entiendo tu punto, pero** una cola agrega otro servicio que mantener.'],
    module: 6,
  },
  {
    es: 'lo veo distinto',
    context: 'Para discordar de uma ideia',
    pt: 'vejo diferente',
    examples: ['**Lo veo distinto**: el problema no son los servidores, sino las queries.'],
    module: 6,
  },
  {
    es: 'perdón que te interrumpa',
    context: 'Para pedir a palavra numa reunião',
    pt: 'desculpa te interromper',
    examples: ['**Perdón que te interrumpa**, pero eso ya lo probamos.'],
    module: 6,
  },
  {
    es: 'volviendo a',
    context: 'Para retomar um assunto na reunião',
    pt: 'voltando a',
    examples: ['**Volviendo a** lo de la cola…'],
    module: 6,
  },
  {
    es: 'quedar en',
    context: 'Para fechar o que foi combinado na reunião',
    pt: 'combinar',
    examples: ['Entonces, ¿**quedamos en** usar Postgres?'],
    module: 6,
  },
  {
    es: 'presentar',
    context: 'Na demo; nunca "apresentar"',
    pt: 'apresentar',
    examples: ['Lucas **presenta** una demo para toda la empresa.'],
    module: 6,
  },
  {
    es: 'les voy a mostrar',
    context: 'Para abrir uma demo',
    pt: 'vou mostrar para vocês',
    examples: ['**Les voy a mostrar** el nuevo sistema de correos.'],
    module: 6,
  },
  {
    es: 'hasta ahora',
    context: 'Na demo, para contar como era antes da mudança',
    pt: 'até agora',
    examples: ['**Hasta ahora**, los correos llegan con una hora de retraso.'],
    module: 6,
  },
  {
    es: 'como ven',
    context: 'Na demo, enquanto mostra algo na tela',
    pt: 'como vocês podem ver',
    examples: ['**Como ven**, el reporte carga en dos segundos.'],
    module: 6,
  },
  {
    es: 'averiguar',
    context: 'Para responder uma pergunta que você não sabe',
    pt: 'descobrir, averiguar',
    examples: ['No lo sé, pero lo **averiguo** y te aviso.'],
    module: 6,
  },
  {
    es: 'los próximos pasos',
    context: 'Para fechar uma demo ou reunião',
    pt: 'os próximos passos',
    examples: ['**Los próximos pasos** son medir el tráfico y separar el servicio.'],
    module: 6,
  },
  {
    es: 'el correo',
    context: 'Palavra do texto: o e-mail',
    pt: 'o e-mail',
    examples: ['Como ven, el **correo** llega en dos segundos.'],
    module: 6,
  },
  {
    es: 'soportar',
    context: 'Palavra do texto: a carga que um sistema aguenta',
    pt: 'aguentar, suportar',
    examples: ['¿Cuántos correos **soporta** por minuto?'],
    module: 6,
  },
  {
    es: 'ponerse nervioso',
    context: 'Palavra do texto: ficar nervoso',
    pt: 'ficar nervoso',
    examples: ['Lucas no **se pone nervioso**.'],
    module: 6,
  },
]
